// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgD15NzQ-GeWyWAw-9T7RxTn1J5n2cSZo',
    appId: '1:721926180347:web:fa6649095ebf4e89db4f5e',
    messagingSenderId: '721926180347',
    projectId: 'todo-app-704fb',
    authDomain: 'todo-app-704fb.firebaseapp.com',
    storageBucket: 'todo-app-704fb.appspot.com',
    measurementId: 'G-Y0MRW1HGF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnpuTFiGOwWnjtzURvNqj5d4HiiY6E0OI',
    appId: '1:721926180347:android:3b001c3bddca2268db4f5e',
    messagingSenderId: '721926180347',
    projectId: 'todo-app-704fb',
    storageBucket: 'todo-app-704fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ3gPyDnkh-fHy7qhiNHtgHeCsrOVe7wg',
    appId: '1:721926180347:ios:4279d075b1a061e9db4f5e',
    messagingSenderId: '721926180347',
    projectId: 'todo-app-704fb',
    storageBucket: 'todo-app-704fb.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ3gPyDnkh-fHy7qhiNHtgHeCsrOVe7wg',
    appId: '1:721926180347:ios:4279d075b1a061e9db4f5e',
    messagingSenderId: '721926180347',
    projectId: 'todo-app-704fb',
    storageBucket: 'todo-app-704fb.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgD15NzQ-GeWyWAw-9T7RxTn1J5n2cSZo',
    appId: '1:721926180347:web:b73e8a37882f49aadb4f5e',
    messagingSenderId: '721926180347',
    projectId: 'todo-app-704fb',
    authDomain: 'todo-app-704fb.firebaseapp.com',
    storageBucket: 'todo-app-704fb.appspot.com',
    measurementId: 'G-T0SSLKRW9P',
  );

}